"""Initialize DB

Revision ID: 499ed575b654
Revises: 
Create Date: 2026-02-22 12:59:29.771405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '499ed575b654'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guru_product_id', sa.String(length=255), nullable=False),
    sa.Column('guru_internal_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('conteudo_programatico', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registration_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey')),
    sa.UniqueConstraint('guru_product_id', name=op.f('courses_guru_product_id_key'))
    )
    op.create_index(op.f('courses_created_at_idx'), 'courses', ['created_at'], unique=False)
    op.create_index(op.f('courses_updated_at_idx'), 'courses', ['updated_at'], unique=False)
    op.create_table('certificate_emissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=500), nullable=False),
    sa.Column('contact_cpf', sa.String(length=14), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('guru_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('certificate_emissions_course_id_courses_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certificate_emissions_pkey'))
    )
    op.create_index(op.f('certificate_emissions_contact_cpf_idx'), 'certificate_emissions', ['contact_cpf'], unique=False)
    op.create_index(op.f('certificate_emissions_created_at_idx'), 'certificate_emissions', ['created_at'], unique=False)
    op.create_index(op.f('certificate_emissions_token_idx'), 'certificate_emissions', ['token'], unique=True)
    op.create_index(op.f('certificate_emissions_updated_at_idx'), 'certificate_emissions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('certificate_emissions_updated_at_idx'), table_name='certificate_emissions')
    op.drop_index(op.f('certificate_emissions_token_idx'), table_name='certificate_emissions')
    op.drop_index(op.f('certificate_emissions_created_at_idx'), table_name='certificate_emissions')
    op.drop_index(op.f('certificate_emissions_contact_cpf_idx'), table_name='certificate_emissions')
    op.drop_table('certificate_emissions')
    op.drop_index(op.f('courses_updated_at_idx'), table_name='courses')
    op.drop_index(op.f('courses_created_at_idx'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
